uint64 INSERT=1
uint64 REMOVE=2
uint64 CONTROL=3
uint64 CLEAR=4
uint64 action
quasimodo_msgs/model model
string object_id
uint64[] vocabulary_ids
---
uint64 vocabulary_id
string object_id
bool control_good
